// --- rules.js ---
// Classification engine: assigns each transaction a {category, group, label}
// based on a configurable rule set ("SETTING"). Rules are regexes matched
// against Name / Verwendungszweck / (bank-provided) Kategorie.
//
// A rule set can be authored by hand in the UI, or generated by an LLM that
// was given the CSV export and the schema documented in README.md, then
// imported via the "Regeln importieren" button.

const STORAGE_KEY = 'classificationRules';
const FALLBACK_GROUP = 'unclassified';

let defaultRuleSet = null;

export async function load_default_rule_set() {
  if (defaultRuleSet) return defaultRuleSet;
  const res = await fetch('./src/default_rules.json');
  defaultRuleSet = await res.json();
  return defaultRuleSet;
}

export function get_stored_rule_set() {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) return null;
  try {
    return JSON.parse(stored);
  } catch (e) {
    console.error('Failed to parse stored classification rules', e);
    return null;
  }
}

export function save_rule_set(ruleSet) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(ruleSet));
}

export function group_meta(ruleSet, groupId) {
  const g = (ruleSet.groups || []).find(g => g.id === groupId);
  return g || { id: groupId, label: groupId, color: '#95a5a6' };
}

function safe_regex(pattern) {
  if (!pattern) return null;
  try {
    return new RegExp(pattern, 'i');
  } catch (e) {
    console.error('Invalid regex in rule:', pattern, e);
    return null;
  }
}

// Returns true if `rule` matches transaction `tx`.
// Each of namePattern / verwendungPattern / kategoriePattern is optional;
// non-empty patterns present must satisfy matchType ('and' = all present
// patterns must match, 'or' = any present pattern matches).
export function rule_matches(tx, rule) {
  const checks = [];
  if (rule.namePattern && rule.namePattern.trim() !== '') {
    const re = safe_regex(rule.namePattern);
    checks.push(re ? re.test(tx.name || tx.Name || '') : false);
  }
  if (rule.verwendungPattern && rule.verwendungPattern.trim() !== '') {
    const re = safe_regex(rule.verwendungPattern);
    checks.push(re ? re.test(tx.verwendungszweck || tx.Verwendungszweck || '') : false);
  }
  if (rule.kategoriePattern && rule.kategoriePattern.trim() !== '') {
    const re = safe_regex(rule.kategoriePattern);
    checks.push(re ? re.test(tx.Kategorie || '') : false);
  }
  if (checks.length === 0) return false;
  return rule.matchType === 'and' ? checks.every(Boolean) : checks.some(Boolean);
}

function fallback_group_for_category(ruleSet, topCategory) {
  const map = ruleSet.categoryGroupFallback || {};
  return map[(topCategory || '').toLowerCase()] || FALLBACK_GROUP;
}

// Classifies a single transaction against a rule set (highest priority
// rule wins). Falls back to the bank-provided Kategorie hierarchy (mapped
// to a group via categoryGroupFallback) if no rule matches, and finally to
// 'Unklassifiziert'.
export function classify(tx, ruleSet) {
  const rules = [...(ruleSet.rules || [])].sort((a, b) => (b.priority || 0) - (a.priority || 0));
  for (const rule of rules) {
    if (rule_matches(tx, rule)) {
      return {
        ruleId: rule.id,
        label: rule.label,
        category: rule.category || rule.label,
        group: rule.group || FALLBACK_GROUP,
        excluded: !!rule.excludeFromTotals,
        source: 'rule'
      };
    }
  }
  const bankKategorie = tx.Kategorie && tx.Kategorie.trim();
  if (bankKategorie) {
    // MoneyMoney/DKB exports nest categories as "AUSGABEN - <Bereich> - <Detail>"
    // or "EINNAHMEN - <Detail>". The leading AUSGABEN/EINNAHMEN segment itself
    // carries no useful grouping info, so fall back to the segment after it.
    const parts = bankKategorie.split(' - ');
    const top = parts[0] === 'EINNAHMEN' ? 'einnahmen' : (parts[1] || parts[0]);
    const leaf = parts[parts.length - 1];
    return {
      ruleId: null,
      label: leaf,
      category: bankKategorie,
      group: fallback_group_for_category(ruleSet, top),
      excluded: false,
      source: 'bank'
    };
  }
  return {
    ruleId: null,
    label: 'Unklassifiziert',
    category: 'Unklassifiziert',
    group: FALLBACK_GROUP,
    excluded: false,
    source: 'none'
  };
}

// Classifies every row in `rows` and caches the result on row._cls.
// Call again whenever the rule set changes.
export function classify_all(rows, ruleSet) {
  rows.forEach(r => { r._cls = classify(r, ruleSet); });
  return rows;
}
